language: node_js
node_js:
    - 10
cache: yarn
install:
    - yarn
script:
    - yarn build
after_success:
    - cd html/.vuepress/dist
    - git init
    - git config --global user.name "${NAME}"
    - git config --global user.email "${EMAIL}"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:${BRANCH}